Game.preloader_unity_2_3_1=function(game){
	this.preloadBar=null;
};

Game.preloader_unity_2_3_1.prototype={
	preload:function(){
		var basePath = window.baseUrl || '';

		// Game-specific assets (unity/2.3.1)
		this.load.atlas('unity2_1_1_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.atlas('unity2_6_1_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_1_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_1_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.image('unity2_6_1_timerbg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_1_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_1_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_1_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_1_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_1_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_1_1_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.atlas('unity2_1_1_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_1_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_1_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Cunity2_1_1_aterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_1_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_2_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_3_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_1_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_1_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_1_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_1_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_1_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_1_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_1_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_1_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_2_1_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('unity2_2_1_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.image('Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Caterpillar_Body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.image('Caterpillar_Body11', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Caterpillar_Body21', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Caterpillar_Body31', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_2_1_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('start1', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_1_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_1_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_1_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_1_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_1starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_1navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_1timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_1CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_1BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_1practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_1topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_1Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_3_1Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_3_1Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_3_1start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_1Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_1Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_1Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_1wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_1starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_1navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_1timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_1CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_1BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_1practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_1topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_1Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_4_1Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_4_1Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_4_1start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_1Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_1Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_1Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_1wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_1starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_1navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_1timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_1CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_1BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_1practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_1topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_1Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_5_1Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_5_1Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_5_1start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_1Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_1Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_1Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_1wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_1a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_1a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_1a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_1a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_1a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_1a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_1a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_1a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_1_1a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_1_1a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_1_1a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_1_1a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_1a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_1a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_1_1a_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_1a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_1a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_1a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_1a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_1a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_1a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_1a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_1a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_2_1a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_2_1a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_2_1a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_2_1a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_1a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_1a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_1a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_1astarAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_1anavBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_1atimebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_1aCommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_1aBG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_1apractice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_1atopic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_1aCaterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_3_1aCaterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_3_1aCaterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_3_1astart', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_1aTick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_1aCaterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_1aCaterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_1awrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_1a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_1a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_1a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_1a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_1a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_1a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_1a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_1a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_4_1a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_4_1a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_4_1a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_1a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_1a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_1a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_1a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_1astarAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_1anavBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_1atimebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_1aCommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_1aBG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_1apractice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_1atopic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_1aCaterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_5_1aCaterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_5_1aCaterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_5_1astart', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_1aTick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_1aCaterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_1aCaterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_1awrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_2_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_2_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_2_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.image('unity2_6_2_timerbg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_2_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_2_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_2_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_2_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_2_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_1_2_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.atlas('unity2_1_2_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_2_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_2_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Cunity2_1_2_aterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_2_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_2_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_2_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_2_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_2_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_2_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_2_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_2_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_2_2_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('unity2_2_2_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('unity2_2_2_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_2_2_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_2_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_2_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_2_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_2starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_2navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_2timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_2CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_2BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_2practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_2topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_2Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_3_2Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_3_2Caterpillar_Body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_3_2start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_2Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_2Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_2Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_2wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_2starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_2navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_2timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_2CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_2BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_2practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_2topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_2Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_4_2Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_4_2Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_4_2start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_2Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_2Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_2Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_2wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_2starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_2navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_2timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_2CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_2BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_2practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_2topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_2Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_5_2Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_5_2Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_5_2start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_2Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_2Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_2Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_2wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_2a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_2a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_2a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_2a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_2a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_2a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_2a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_2a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_1_2a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_1_2a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_1_2a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_1_2a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_2a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_2a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_1_2a_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_2a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_2a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_2a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_2a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_2a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_2a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_2a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_2a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_2_2a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_2_2a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_2_2a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_2_2a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_2a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_2a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_2a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_2astarAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_2anavBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_2atimebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_2aCommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_2aBG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_2apractice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_2atopic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_2aCaterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_3_2aCaterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_3_2aCaterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_3_2astart', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_2aTick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_2aCaterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_2aCaterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_2awrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_2a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_2a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_2a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_2a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_2a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_2a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_2a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_2a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_4_2a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_4_2a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_4_2a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_2a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_2a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_2a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_2a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_2astarAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_2anavBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_2atimebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_2aCommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_2aBG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_2apractice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_2atopic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_2aCaterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_5_2aCaterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_5_2aCaterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_5_2astart', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_2aTick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_2aCaterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_2aCaterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_2awrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_3_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_3_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_3_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.image('unity2_6_3_timerbg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_3_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_3_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_3_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_3_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_3_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_1_3_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.atlas('unity2_1_3_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_3_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_3_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Cunity2_1_3_aterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_3_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_3_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_3_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_3_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_3_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_3_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_3_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_3_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('unity2_2_3_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('unity2_2_3_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('unity2_2_3_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_2_3_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_3_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_3_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_3_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_3starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_3navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_3timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_3CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_3BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_3practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_3topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_3Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_3_3Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_3_3Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_3_3start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_3Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_3Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_3Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_3wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_3starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_3navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_3timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_3CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_3BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_3practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_3topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_3Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_4_3Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_4_3Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_4_3start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_3Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_3Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_3Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_3wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_3starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_3navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_3timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_3CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_3BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_3practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_3topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_3Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1.png');
		this.load.image('Unity2_5_3Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2.png');
		this.load.image('Unity2_5_3Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_new.png');
		this.load.atlas('Unity2_5_3start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_3Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_3Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_3Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_3wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_1_3a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_1_3a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_1_3a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_1_3a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_1_3a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_1_3a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_1_3a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_1_3a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_1_3a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_1_3a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_1_3a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_1_3a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_1_3a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_1_3a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_1_3a_Caterpillar_Sad', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('unity2_2_3a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('unity2_2_3a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('unity2_2_3a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('unity2_2_3a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('unity2_2_3a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('unity2_2_3a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('unity2_2_3a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('unity2_2_3a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('unity2_2_3a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('unity2_2_3a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('unity2_2_3a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('unity2_2_3a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('unity2_2_3a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('unity2_2_3a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('unity2_2_3a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_3_3a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_3_3a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_3_3a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_3_3a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_3_3a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_3_3a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_3_3a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_3_3a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_3_3a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_3_3a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_3_3a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_3_3a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_3_3a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_3_3a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_3_3a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_4_3a_starAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_4_3a_navBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_4_3a_timebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_4_3a_CommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_4_3a_BG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_4_3a_practice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_4_3a_topic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_4_3a_Caterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_4_3a_Caterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_4_3a_Caterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_4_3a_start', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_4_3a_Tick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_4_3a_Caterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_4_3a_Caterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_4_3a_wrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');
		this.load.atlas('Unity2_5_3astarAnim',basePath+'assets/commonAssets/starAnim1.png',basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('Unity2_5_3anavBar',basePath+'assets/commonAssets/topbar.png');
		this.load.image('Unity2_5_3atimebg',basePath+'assets/commonAssets/timebg.png');
		this.load.atlas('Unity2_5_3aCommonSpeakerBtn',basePath+'assets/commonAssets/grade11_speaker.png',basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Unity2_5_3aBG_01', basePath+'assets/gradeAssets/2.1.1/BG_01.png');
		this.load.image('Unity2_5_3apractice',basePath+'assets/gradeAssets/2.1.1/practice.png');
		this.load.image('Unity2_5_3atopic',basePath+'assets/gradeAssets/2.1.1/topic.png');
		this.load.image('Unity2_5_3aCaterpillar_Body1', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body1Reverse.png');
		this.load.image('Unity2_5_3aCaterpillar_Body2', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Body2Reverse.png');
		this.load.image('Unity2_5_3aCaterpillar_body3', basePath+'assets/gradeAssets/2.1.1/Caterpillar_body_newReverse.png');
		this.load.atlas('Unity2_5_3astart', basePath+'assets/gradeAssets/2.1.1/start.png', basePath+'assets/gradeAssets/2.1.1/start.json');
		this.load.atlas('Unity2_5_3aTick', basePath+'assets/gradeAssets/2.1.1/tick.png', basePath+'assets/gradeAssets/2.1.1/tick.json');
		this.load.atlas('Unity2_5_3aCaterpillar_Neutral', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Neutral.json');
		this.load.atlas('Unity2_5_3aCaterpillar_Happy', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Happy.json');
		this.load.atlas('Unity2_5_3awrong', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.png', basePath+'assets/gradeAssets/2.1.1/Caterpillar_Sad.json');

		// Common UI assets  (all paths inside assets/commonAssets/ — no separate json/ folder)
		this.load.image('prgressbarOutLine', basePath+'assets/commonAssets/prgressbarOutLine.png');
		this.load.image('preloadBar',        basePath+'assets/commonAssets/prgressbar.png');
		this.load.atlas('newCommonBackBtnForAll', basePath+'assets/commonAssets/newBackBtn.png',      basePath+'assets/commonAssets/newBackBtn.json');
		this.load.atlas('grade11_speaker',        basePath+'assets/commonAssets/grade11_speaker.png', basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Level42C_Topbar',        basePath+'assets/commonAssets/Topbar.png');
		this.load.image('Level42C_timer',         basePath+'assets/commonAssets/timer.png');
		this.load.atlas('starAnim1',              basePath+'assets/commonAssets/starAnim1.png',       basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('CommonBackground',       basePath+'assets/commonAssets/commonBg.png');
		this.load.image('commonBg1', basePath+'assets/commonAssets/commonBg1.png');
		this.load.image('commonBg2', basePath+'assets/commonAssets/commonBg2.png');

		// Score screen buttons (local)
		this.load.image('CommonHomeBtn',   'assets/homeIconScore.png');
		this.load.image('CommonNextBtn',   'assets/nextIconScore.png');
		this.load.image('CommonReplayBtn', 'assets/replayIconScore.png');
		this.load.image('shareIconScore',  'assets/shareIconScore.png');





		// Shared sounds (from BB preloader main body — all games need these)
		this.load.audio('waudio', 'sounds/WrongCelebrationSound.mp3');
		this.load.audio('ClickSound', 'sounds/ClickSound.mp3');
		this.load.audio('celebr', 'sounds/celebration.mp3');
		this.load.audio('snapSound', 'sounds/snapSound.mp3');
		this.load.audio('goingdown', 'sounds/goingdown.mp3');
		this.load.audio('goingup', 'sounds/goingup.mp3');
		this.load.audio('spin2', 'sounds/spin2.mp3');
		this.load.audio('waterFill', 'sounds/waterFillingSound.mp3');
		this.load.audio('watersplash', 'sounds/watersplash.mp3');
		this.load.audio('clocktick', 'sounds/clocktick.mp3');
		this.load.audio('click', 'sounds/chime.mp3');
		this.load.audio('tinklesound', 'sounds/tinkle.mp3');
		this.load.audio('slide', 'sounds/slidingsound.mp3');
		this.load.audio('roll', 'sounds/rollingsound.mp3');
		this.load.audio('dragsnapsound', 'sounds/Drag_Snap.mp3');
		this.load.audio('snakeSound', 'sounds/snake.mp3');
		this.load.audio('ladderSound', 'sounds/ladder.mp3');
		this.load.audio('autoSound', 'sounds/autoSound.mp3');
		this.load.audio('CarrotBite', 'sounds/CarrotBite.mp3');
		this.load.audio('Rabbit', 'sounds/Rabbit.mp3');
		this.load.audio('Tap', 'sounds/Tap.mp3');
		this.load.audio('tap', 'sounds/Tap.mp3');
		this.load.audio('EHowMany', 'sounds/EHowMany.mp3');
		this.load.audio('HHowMany', 'sounds/HHowMany.mp3');
		this.load.audio('KHowMany', 'sounds/KHowMany.mp3');
		this.load.audio('dragMango', 'sounds/Drag_Snap.mp3');
		this.load.audio('bubble', 'sounds/Bubbles.mp3');
		this.load.audio('bubbleBurst', 'sounds/Bubble Burst.mp3');
		this.load.audio('coinFall', 'sounds/CoinDrop.mp3');
		this.load.audio('cashOut', 'sounds/CashOut.mp3');
		this.load.audio('WaterDropSplash', 'sounds/WaterDropSplash.mp3');
		this.load.audio('anim1sound', 'sounds/Mouse.mp3');
		this.load.audio('anim2sound', 'sounds/Elephant.mp3');
		this.load.audio('buzzSound', 'sounds/buzzsound.mp3');
		this.load.audio('RabbitSound', 'sounds/Rabbit.mp3');
		this.load.audio('ClungSound', 'sounds/clung.mp3');
		this.load.audio('eggCrack', 'sounds/eggCrack.mp3');
		this.load.audio('RabbitMovingSound', 'sounds/rabbitMovingSound.mp3');
		this.load.audio('lockSound1', 'sounds/locksound1.mp3');
		this.load.audio('lockSound2', 'sounds/locksound2.mp3');
		this.load.audio('scrollSound', 'sounds/tick1.mp3');
	},

	create:function(){
		this.state.start('unity2_3_1level1');
	},
};
