Game.preloader_longdivision4=function(game){
	this.preloadBar=null;
};

Game.preloader_longdivision4.prototype={
	preload:function(){
		var basePath = window.baseUrl || '';

		// Game-specific assets (longdivision4)
		this.load.image('nsnpg1_3skipDemoVideos',basePath+'assets/NSN1/commonAssets/skipArrow.png');
		this.load.atlas('nsnpg1_3backbtn',basePath+'assets/NSN1/commonAssets/backbtn.png' ,basePath+'json/NSN1/gradeJson/backbtn.json');
		this.load.atlas('nsnpg1_3CommonSpeakerBtn',basePath+'assets/NSN1/commonAssets/speaker.png' ,basePath+'json/NSN1/gradeJson/speaker.json');
		this.load.atlas('nsnpg1_3starAnim',basePath+'assets/NSN1/commonAssets/starAnim.png',basePath+'json/NSN1/gradeJson/starAnim.json');
		this.load.atlas('nsnpg1_3replay',basePath+'assets/NSN1/commonAssets/reply.png' ,basePath+'json/NSN1/gradeJson/reply.json');
		this.load.atlas('nsnpg1_3btn',basePath+'assets/NSN1/commonAssets/btn.png',basePath+'json/NSN1/gradeJson/btn.json');
		this.load.image('nsnpg1_3background1',basePath+'assets/NSN1/commonAssets/bg1.png');
		this.load.image('nsnpg1_3tittleBar',basePath+'assets/NSN1/commonAssets/tittleBar.png');
		this.load.image('nsnpg1_3navBar',basePath+'assets/NSN1/commonAssets/navBar.png');
		this.load.image('nsnpg1_3timebg',basePath+'assets/NSN1/commonAssets/timebg.png');
		this.load.atlas('nsnpg1_3_erase',basePath+'assets/NSN1/commonAssets/erase.png' ,basePath+'json/NSN1/gradeJson/erase.json');
		this.load.atlas('nsnpg1_3_rightmark',basePath+'assets/NSN1/commonAssets/rightmark.png' ,basePath+'json/NSN1/gradeJson/rightmark.json');
		this.load.image('nsnpg1_3_numBG',basePath+'assets/NSN1/commonAssets/b2.png');
		this.load.atlas('nsnpg1_3_numberpad',basePath+'assets/NSN1/commonAssets/calNum.png',basePath+'json/NSN1/gradeJson/calNum.json');
		this.load.atlas('nsnpg1_3_numbers1',basePath+'assets/NSN1/commonAssets/numbers1.png',basePath+'json/NSN1/gradeJson/numbers1.json');
		this.load.image('nsnpg1_3background',basePath+'assets/NSN1/gradeAssets/Bg.png');
		this.load.atlas('nsnpg1_3imageBox',basePath+'assets/NSN1/gradeAssets/imageBox.png',basePath+'json/NSN1/gradeJson/imageBox.json');
		this.load.image('nsnpg1_3whiteBox',basePath+'assets/NSN1/gradeAssets/whiteBox.png');
		this.load.atlas('nsnpg1_3numberBox',basePath+'assets/NSN1/gradeAssets/numberBox.png',basePath+'json/NSN1/gradeJson/numberBox.json');
		this.load.image('nsnpg1_3fullimage1',basePath+'assets/NSN1/gradeAssets/image1Shapes/full image1.png');
		this.load.image('nsnpg1_3shape1_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_1',basePath+'assets/NSN1/gradeAssets/image1Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage2',basePath+'assets/NSN1/gradeAssets/image2Shapes/full image2.png');
		this.load.image('nsnpg1_3shape1_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_2',basePath+'assets/NSN1/gradeAssets/image2Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage3',basePath+'assets/NSN1/gradeAssets/image3Shapes/full image3.png');
		this.load.image('nsnpg1_3shape1_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_3',basePath+'assets/NSN1/gradeAssets/image3Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage4',basePath+'assets/NSN1/gradeAssets/image4Shapes/full image4.png');
		this.load.image('nsnpg1_3shape1_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_4',basePath+'assets/NSN1/gradeAssets/image4Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage5',basePath+'assets/NSN1/gradeAssets/image5Shapes/full image5.png');
		this.load.image('nsnpg1_3shape1_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_5',basePath+'assets/NSN1/gradeAssets/image5Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage6',basePath+'assets/NSN1/gradeAssets/image6Shapes/full image6.png');
		this.load.image('nsnpg1_3shape1_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_6',basePath+'assets/NSN1/gradeAssets/image6Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage7',basePath+'assets/NSN1/gradeAssets/image7Shapes/full image7.png');
		this.load.image('nsnpg1_3shape1_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_7',basePath+'assets/NSN1/gradeAssets/image7Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage8',basePath+'assets/NSN1/gradeAssets/image8Shapes/full image8.png');
		this.load.image('nsnpg1_3shape1_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_8',basePath+'assets/NSN1/gradeAssets/image8Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage9',basePath+'assets/NSN1/gradeAssets/image9Shapes/full image9.png');
		this.load.image('nsnpg1_3shape1_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_9',basePath+'assets/NSN1/gradeAssets/image9Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage10',basePath+'assets/NSN1/gradeAssets/image10Shapes/full image10.png');
		this.load.image('nsnpg1_3shape1_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_10',basePath+'assets/NSN1/gradeAssets/image10Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage11',basePath+'assets/NSN1/gradeAssets/image11Shapes/full image11.png');
		this.load.image('nsnpg1_3shape1_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_11',basePath+'assets/NSN1/gradeAssets/image11Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage12',basePath+'assets/NSN1/gradeAssets/image12Shapes/full image12.png');
		this.load.image('nsnpg1_3shape1_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_12',basePath+'assets/NSN1/gradeAssets/image12Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage13',basePath+'assets/NSN1/gradeAssets/image13Shapes/full image13.png');
		this.load.image('nsnpg1_3shape1_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_13',basePath+'assets/NSN1/gradeAssets/image13Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage14',basePath+'assets/NSN1/gradeAssets/image14Shapes/full image14.png');
		this.load.image('nsnpg1_3shape1_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_14',basePath+'assets/NSN1/gradeAssets/image14Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage15',basePath+'assets/NSN1/gradeAssets/image15Shapes/full image15.png');
		this.load.image('nsnpg1_3shape1_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_15',basePath+'assets/NSN1/gradeAssets/image15Shapes/shape9.png');
		this.load.image('nsnpg1_3fullimage16',basePath+'assets/NSN1/gradeAssets/image16Shapes/full image16.png');
		this.load.image('nsnpg1_3shape1_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape1.png');
		this.load.image('nsnpg1_3shape2_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape2.png');
		this.load.image('nsnpg1_3shape3_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape3.png');
		this.load.image('nsnpg1_3shape4_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape4.png');
		this.load.image('nsnpg1_3shape5_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape5.png');
		this.load.image('nsnpg1_3shape6_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape6.png');
		this.load.image('nsnpg1_3shape7_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape7.png');
		this.load.image('nsnpg1_3shape8_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape8.png');
		this.load.image('nsnpg1_3shape9_16',basePath+'assets/NSN1/gradeAssets/image16Shapes/shape9.png');

		// Common UI assets  (all paths inside assets/commonAssets/ — no separate json/ folder)
		this.load.image('prgressbarOutLine', basePath+'assets/commonAssets/prgressbarOutLine.png');
		this.load.image('preloadBar',        basePath+'assets/commonAssets/prgressbar.png');
		this.load.atlas('newCommonBackBtnForAll', basePath+'assets/commonAssets/newBackBtn.png',      basePath+'assets/commonAssets/newBackBtn.json');
		this.load.atlas('grade11_speaker',        basePath+'assets/commonAssets/grade11_speaker.png', basePath+'assets/commonAssets/grade11_speaker.json');
		this.load.image('Level42C_Topbar',        basePath+'assets/commonAssets/Topbar.png');
		this.load.image('Level42C_timer',         basePath+'assets/commonAssets/timer.png');
		this.load.atlas('starAnim1',              basePath+'assets/commonAssets/starAnim1.png',       basePath+'assets/commonAssets/starAnim1.json');
		this.load.image('CommonBackground',       basePath+'assets/commonAssets/commonBg.png');
		this.load.image('commonBg1', basePath+'assets/commonAssets/commonBg1.png');
		this.load.image('commonBg2', basePath+'assets/commonAssets/commonBg2.png');

		// Score screen buttons (local)
		this.load.image('CommonHomeBtn',   'assets/homeIconScore.png');
		this.load.image('CommonNextBtn',   'assets/nextIconScore.png');
		this.load.image('CommonReplayBtn', 'assets/replayIconScore.png');
		this.load.image('shareIconScore',  'assets/shareIconScore.png');


		// Shared images/atlases from BB preloader (keys this game references)
		this.load.atlas('CommonBackBtn', basePath+'assets/commonAssets/backbtn.png', basePath+'assets/commonAssets/backbtn.json');
		this.load.atlas('CommonSpeakerBtn', basePath+'assets/commonAssets/speaker.png', basePath+'assets/commonAssets/speaker.json');
		this.load.atlas('eraser', basePath+'assets/gradeAssets/4.3A/commonAssets/eraser.png', basePath+'assets/gradeAssets/4.3A/eraser.json');
		this.load.image('longdivision4', basePath+'assets/newGames/longdivision4.png');
		this.load.image('longdivision6', basePath+'assets/newGames/longdivision6.png');



		// Shared sounds (from BB preloader main body — all games need these)
		this.load.audio('waudio', 'sounds/WrongCelebrationSound.mp3');
		this.load.audio('ClickSound', 'sounds/ClickSound.mp3');
		this.load.audio('celebr', 'sounds/celebration.mp3');
		this.load.audio('snapSound', 'sounds/snapSound.mp3');
		this.load.audio('goingdown', 'sounds/goingdown.mp3');
		this.load.audio('goingup', 'sounds/goingup.mp3');
		this.load.audio('spin2', 'sounds/spin2.mp3');
		this.load.audio('waterFill', 'sounds/waterFillingSound.mp3');
		this.load.audio('watersplash', 'sounds/watersplash.mp3');
		this.load.audio('clocktick', 'sounds/clocktick.mp3');
		this.load.audio('click', 'sounds/chime.mp3');
		this.load.audio('tinklesound', 'sounds/tinkle.mp3');
		this.load.audio('slide', 'sounds/slidingsound.mp3');
		this.load.audio('roll', 'sounds/rollingsound.mp3');
		this.load.audio('dragsnapsound', 'sounds/Drag_Snap.mp3');
		this.load.audio('snakeSound', 'sounds/snake.mp3');
		this.load.audio('ladderSound', 'sounds/ladder.mp3');
		this.load.audio('autoSound', 'sounds/autoSound.mp3');
		this.load.audio('CarrotBite', 'sounds/CarrotBite.mp3');
		this.load.audio('Rabbit', 'sounds/Rabbit.mp3');
		this.load.audio('Tap', 'sounds/Tap.mp3');
		this.load.audio('tap', 'sounds/Tap.mp3');
		this.load.audio('EHowMany', 'sounds/EHowMany.mp3');
		this.load.audio('HHowMany', 'sounds/HHowMany.mp3');
		this.load.audio('KHowMany', 'sounds/KHowMany.mp3');
		this.load.audio('dragMango', 'sounds/Drag_Snap.mp3');
		this.load.audio('bubble', 'sounds/Bubbles.mp3');
		this.load.audio('bubbleBurst', 'sounds/Bubble Burst.mp3');
		this.load.audio('coinFall', 'sounds/CoinDrop.mp3');
		this.load.audio('cashOut', 'sounds/CashOut.mp3');
		this.load.audio('WaterDropSplash', 'sounds/WaterDropSplash.mp3');
		this.load.audio('anim1sound', 'sounds/Mouse.mp3');
		this.load.audio('anim2sound', 'sounds/Elephant.mp3');
		this.load.audio('buzzSound', 'sounds/buzzsound.mp3');
		this.load.audio('RabbitSound', 'sounds/Rabbit.mp3');
		this.load.audio('ClungSound', 'sounds/clung.mp3');
		this.load.audio('eggCrack', 'sounds/eggCrack.mp3');
		this.load.audio('RabbitMovingSound', 'sounds/rabbitMovingSound.mp3');
		this.load.audio('lockSound1', 'sounds/locksound1.mp3');
		this.load.audio('lockSound2', 'sounds/locksound2.mp3');
		this.load.audio('scrollSound', 'sounds/tick1.mp3');
	},

	create:function(){
		this.state.start('longdivision4');
	},
};
